# Generated by Django 4.0.2 on 2022-03-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todonotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='href',
        ),
    ]
